### ISSUE TITLE
gem?

### ISSUE THREAD

**Issue by dcalixto** [episource/jekyll-uncss#3]
jekyll build JEKYLL_ENV=production
Configuration file: /home/maria/ruby/ddd/_config.yml
  Dependency Error: Yikes! It looks like you don't have /home/maria/ruby/ddd/_plugins/jekyll-uncss/uncss.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the /home/maria/ruby/ddd/_plugins/jekyll-uncss/uncss.rb gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- sass' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
                    ------------------------------------------------
      Jekyll 4.0.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------

ll/external.rb:73:in `rescue in block in require_with_graceful_fail': /home/maria/ruby/ddd/_plugins/jekyll-uncss/uncss.rb (Jekyll::Errors::MissingDependencyException)

**Comment by episource** [comment]
You are missing the [ruby-sass dependency](https://rubygems.org/gems/sass/).

This dependency is used for compressing/minifying the resulting css. Ruby-Sass is deprecated though. I've not yet updated the plugin to use the recommended replacement sassc instead.
